language: cpp

compiler:
    - gcc
    - clang

os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - boost-latest
    packages:
      - g++-5
      - clang-format-3.8
      - libboost1.55-all-dev
      - cmake-data
      - cmake

before_script:
  - if [ "$CC" = "gcc" ]; then
      export CC=gcc-5 CXX=g++-5;
    fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
      
notifications:
 email:
  on_success: never
  on_failure: always
