language: cpp

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - g++-5
            - libboost1.55-all-dev
            - cmake-data
            - cmake
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - clang-3.8
            - libboost1.55-all-dev
            - cmake-data
            - cmake

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script: make
      
notifications:
 email:
  on_success: never
  on_failure: always
